### ISSUE TITLE
Build is getting failed not Heroku 

### ISSUE THREAD

**Issue by vinaymavi** [areai51/fusion#67]
We are getting build fail on Heroku server 
```remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  8.9.3
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version 8.9.3...
remote:        Downloading and installing node 8.9.3...
remote:        Using default npm version: 5.5.1
remote:        Resolving yarn version 1.x...
remote:        Downloading and installing yarn (1.4.0)...
remote:        Installed yarn 1.4.0
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new-signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.4.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info There appears to be trouble with your network connection. Retrying...
remote:        info fsevents@1.1.3: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        Done in 46.09s.
remote:        Running heroku-postbuild (yarn)
remote:        yarn run v1.4.0
remote:        $ npm run build
remote:
remote:        > fusion@1.0.0 build /tmp/build_5df98f6fac819aae9f9902bfff3952b1
remote:        > next build
remote:
remote: module.js:538
remote:     throw err;
remote:     ^
remote:
remote: Error: Cannot find module 'webpack/lib/RequestShortener'
remote:     at Function.Module._resolveFilename (module.js:536:15)
remote:     at Function.Module._load (module.js:466:25)
remote:     at Module.require (module.js:579:17)
remote:     at require (internal/module.js:11:18)
remote:     at Object.<anonymous> (/tmp/build_5df98f6fac819aae9f9902bfff3952b1/node_modules/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:4:26)
remote:     at Module._compile (module.js:635:30)
remote:     at Object.Module._extensions..js (module.js:646:10)
remote:     at Module.load (module.js:554:32)
remote:     at tryModuleLoad (module.js:497:12)
remote:     at Function.Module._load (module.js:489:3)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! fusion@1.0.0 build: `next build`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the fusion@1.0.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2018-01-21T14_23_28_700Z-debug.log
remote: error An unexpected error occurred: "Command failed.\nExit code: 1\nCommand: sh\nArguments: -c npm run build\nDirectory: /tmp/build_5df98f6fac819aae9f9902bfff3952b1\nOutput:\n".
remote:        info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_5df98f6fac819aae9f9902bfff3952b1/yarn-error.log".
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to sape-fusion.
remote:
To https://git.heroku.com/sape-fusion.git
 ! [remote rejected] master -> master (pre-receive hook declined)

**Comment by vinaymavi** [comment]
PR open https://github.com/pagesource/fusion-components/pull/68

**Comment by vinaymavi** [comment]
As PR is merged closing this issue.
